DELETE FROM utilisateur;
ALTER TABLE utilisateur CHANGE UTI_PSW UTI_PSW VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

ALTER TABLE utilisateur ADD UTI_SCORE INT(4) NULL DEFAULT '0' AFTER UTI_PSW;